site_name: Pousada Animal

theme:
  name: material

nav:
  - Home: "index.md"
  - Projeto:  
    - Visão do Produto: "product-vision.md"
    - Rich Picture: "rich-picture.md"
    - Backlog do Produto: "product-backlog.md"
  - Gerência:
    - Metodologia: "methodology.md"
    - Engenharia de Requisitos: "requirements-engineering.md"
    - Lista de Requisitos inicial: "requirements-list.md"
  - Resultados:
    - Unidade 1: "results/unit-1.md"