site_name: Pousada Animal

repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-PousadaAnimal
repo_name: Pousada Animal

theme:
  name: material
  logo: images/favicon-medio.png
  favicon: images/favicon-medio.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Visão do Produto: "unit-4/product-vision.md" "version-finale/product-vision.md"
  - Engenharia de Requisitos: "unit-3/requirements-engineering.md" "version-finale/requirements-engineering.md"
  - Lista de Requisitos: "unit-2/requirements-list.md" "version-finale/requirements-list.md"
  - Backlog do Produto: "unit-4/product-backlog.md" "version-finale/product-backlog.md"
  - Rich Picture: "unit-2/rich-picture.md" "version-finale/rich-picture.md"
  - Identidade Visual: "unit-1/visual-identity.md" "version-finale/visual-identity.md"
  - Metodologia: "unit-3/methodology.md" "version-finale/methodology.md"
  - Gerenciamento do Projeto: "unit-4/project-management.md" "version-finale/project-management.md"
  - Canvas MVP: "unit-3/canvas-mvp.md" "version-finale/canvas-mvp.md"
  - PBB: "unit-3/pbb.md"
  - User Story Map: "unit-4/user-story-map.md"
  - Casos de Uso:
    - Especificação dos casos MVP2: "version-finale/use-case-client-especification.md"
    - Diagrama de caso de uso: "version-finale/use-case-uml.md"
  - Apresentação: 
    - Apresentação Unidade 1: "version-finale/unit-1-presentation.md"
    - Apresentação Unidade 2: "version-finale/unit-2-presentation.md"
    - Apresentação Unidade 4: "version-finale/unit-4-presentation.md"


