site_name: Pousada Animal

repo_url: https://github.com/FGAUnB-REQ-GM/2021.2-PousadaAnimal
repo_name: Pousada Animal

theme:
  name: material
  logo: images/favicon-medio.png
  favicon: images/favicon-medio.png
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Visão do Produto: "version-finale/product-vision.md"
  - Lista de Requisitos: "version-finale/requirements-list.md"
  - Engenharia de Requisitos: "version-finale/requirements-engineering.md"
  - Backlog do Produto: "version-finale/product-backlog.md"
  - Gerenciamento do Projeto: "version-finale/project-management.md"
  - Metodologia: "version-finale/methodology.md"
  - Rich Picture: "version-finale/rich-picture.md"
  - Identidade Visual: "version-finale/visual-identity.md"
  - Canvas MVP:  "version-finale/canvas-mvp.md"
  - PBB: "version-finale/pbb.md"
  - User Story Map: "version-finale/user-story-map.md"
  - Casos de Uso:
    - Especificação dos casos MVP2: 
      - Pré-agendamento - US17 e US19: "version-finale/use-case-17-19.md"
      - Consultar Status do Animal - US20: "version-finale/user-case-20.md"
      - Informar Status do Animal- US21: "version-finale/user-case-21.md"
    - Diagrama de caso de uso: "version-finale/use-case-uml.md"
  - Apresentação: 
    - Apresentação Unidade 1: "version-finale/unit-1-presentation.md"
    - Apresentação Unidade 2: "version-finale/unit-2-presentation.md"
    - Apresentação Unidade 4: "version-finale/unit-4-presentation.md"
