site_name: Pousada Animal

theme:
  name: material
  logo: images/favicon-medio.png
  favicon: images/favicon-medio.png

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Unidade 1:  
    - Visão do Produto: "unit-1/product-vision.md"
    - Engenharia de Requisitos: "unit-1/requirements-engineering.md"
    - Lista de Requisitos inicial: "unit-1/requirements-list.md"
    - Backlog do Produto: "unit-1/product-backlog.md"
    - Rich Picture: "unit-1/rich-picture.md"
    - Identidade Visual: "unit-1/visual-identity.md"
    - Metodologia: "unit-1/methodology.md"
    - Apresentação: "unit-1/presentation.md"
  - Unidade 2:
    - Canvas MVP: "unit-2/canvas-mvp.md"
