site_name: Pousada Animal

theme:
  name: material
  logo: /images/favicon-medio.png
  favicon: /images/favicon-medio.png

extra_css:
  - stylesheets/extra.css

nav:
  - Home: "index.md"
  - Projeto:  
    - Visão do Produto: "product-vision.md"
    - Identidade Visual: "visual-identity.md"
    - Rich Picture: "rich-picture.md"
    - Backlog do Produto: "product-backlog.md"
    - Canvas MVP: "canvas-mvp.md"
  - Gerência:
    - Metodologia: "methodology.md"
    - Engenharia de Requisitos: "requirements-engineering.md"
    - Lista de Requisitos inicial: "requirements-list.md"
  - Resultados:
    - Unidade 1: "results/unit-1.md"