# Generated by Django 4.0.3 on 2022-03-29 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('weight', models.FloatField()),
                ('medical_conditions', models.TextField(blank=True, max_length=255, null=True)),
                ('temperament', models.CharField(max_length=255)),
                ('is_hosted', models.BooleanField(default=True)),
                ('since', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
