name: Deploy Production 
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  heroku-deploy:
    name: Deploy Backend on Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 47306b24-9e0a-4de5-a6db-e5117d58aec6
          heroku_app_name: pousada-animal
          heroku_email: luis.ggaboardi@gmail.com

  build-front:
    name: Build Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angularFrontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:prod
      - name: Cadê?
        run: ls

  deploy-front:
    name: Deploy Frontend on Firebase
    needs: build-front
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angularFrontend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cadê?
        run: ls
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//0hKohB6datjKWCgYIARAAGBESNwF-L9IrK7Su7n3UDG9Rv-bNstkzrl9iqSw640Mzr1LdxTbJc7KXvCNPBeM6dLwNjfOY_pxeZwM
          PROJECT_PATH: "./angularFrontend"